### ISSUE TITLE
Xin file thiết kế giao diện website

### ISSUE THREAD

**Issue by lamhoang1256** [TranDangKhoi/simple-crowfunding-app#1]
Em thấy project này xịn quá, bác có file thiết kế hay clone lại từ web nào ko cho e xin để có ý tưởng làm dự án đc ko ạ 😃

**Comment by TranDangKhoi** [comment]
> Em thấy project này xịn quá, bác có file thiết kế hay clone lại từ web nào ko cho e xin để có ý tưởng làm dự án đc ko ạ 😃

Thanks bro, dự án này cũng bình thường thôi còn nhiều thứ em bỏ giữa chừng, dự án này em làm theo một thiết kế Figma:

[Crowdfunding Figma Design](https://www.figma.com/file/dYCT6CwqWcuukTZVC7IKU7/crowfunding?node-id=1329%3A21191&t=qMrMYmIX45IB4GmX-1)

Bác có thể xem trực tiếp ở link trên. Nếu muốn edit, bác click vào logo Figma ở góc trái màn hình -> File -> Save local copy 
để tải về (theo em nhớ là vậy). Nếu không được thì em up lên drive

**Comment by lamhoang1256** [comment]
Cảm ơn bác nhé, project xịn lắm ấy hi vọng bác cập nhật thêm nhiều chức năng, với live demo trên vercel, heroku cho tiện theo dõi 😍
